@startuml

skinparam classAttributeIconSize 0

'packages
package "API"
{
    package "Controllers"
    {
        class EmployeeController{
            - repository : EmployeeRepository 
            {method} + all() : Employee
            {method} + newEmployee(newEmployee : Employee) : void
            {method} + one(id :long) : Employee
            {method} + replaceEmployee(newEmployee : Employee, id :long) Employee
            {method} + deleteEmployee(id :long) : void
        }

        class EmployeeNotFoundAdvice{
        {method} + employeeNotFoundHandler(ex : EmployeeNotFoundException) : string
        }

        class EmployeeNotFoundException{
            {method} EmployeeNotFoundException(id :long) : void
        }
    }
}
package "Domain"
{
    package "Entities"
    {
        class Employee{
            - id : long
            - name : string
            - role : string

            {method} + equals(o : Object) : boolean
            {method} + hashCode() : int
            {method} + toString() : string
        }
    }
}

package "Repositories"
{
    interface EmployeeRepository{}
}

'relations
EmployeeController --> Employee
EmployeeController --> EmployeeRepository

EmployeeController ..> EmployeeNotFoundException : throws
EmployeeNotFoundAdvice --> EmployeeNotFoundException
@enduml