@startuml

skinparam classAttributeIconSize 0

'packages
package "API"
{
    package "Controllers"
    {
        class EmployeeController{
            - repository : EmployeeRepository 
            + all() : Employee
            + newEmployee(newEmployee : Employee) : void
            + one(id :long) : Employee
            + replaceEmployee(newEmployee : Employee, id :long) Employee
            + deleteEmployee(id :long) : void
        }

        class DepartementController{
            - repository : DepartementRepository 
            + addEmployee(employee : Employee) : void
            + fireEmployee(employee : Employee) : void
        }

        class DepartementNotFoundAdvice{
            + DepartementNotFoundAdvice(id :long) : void
        }

        class EmployeeNotAvailableException{
            + EmployeeNotAvailableException(id :long) : void
        }

        class EmployeeNotFoundAdvice{
            + employeeNotFoundHandler(ex : EmployeeNotFoundException) : string
        }

        class EmployeeNotFoundException{
            + EmployeeNotFoundException(id :long) : void
        }
    }
}
package "Domain"
{
    package "Entities"
    {
        class Employee{
            - id : long
            - name : string
            - email : string
            - role : string

            + equals(o : Object) : boolean
            + hashCode() : int
            + toString() : string
        }

        class Departement {
            ' - id : long
            - name : string
            
            + Departement()
            + Departement(employee : Employee)
            + availibleEmployee(employee : Employee)
        }
    }
}

package "Repositories"
{
    interface EmployeeRepository{}
    interface DepartementRepository{}
}

'relations
EmployeeController --> Employee
EmployeeController --> EmployeeRepository

EmployeeController ..> EmployeeNotFoundException : throws
EmployeeNotFoundAdvice --> EmployeeNotFoundException

DepartementController --> Employee
DepartementController --> Departement
DepartementController --> DepartementRepository

DepartementController ..> DepartementNotFoundAdvice : throws
DepartementController ..> EmployeeNotAvailableException : throws

@enduml