@startuml

skinparam classAttributeIconSize 0

'packages
package "API"
{
    package "Controllers"
    {
        class EmployeeController{
            - repository : EmployeeRepository 
            + all() : Employee
            + newEmployee(newEmployee : Employee) : void
            + one(id :long) : Employee
            + replaceEmployee(newEmployee : Employee, id :long) Employee
            + deleteEmployee(id :long) : void
        }

        class DepartmentController{
            - repository : DepartmentRepository 

            + newDepartment(newDepartment : Department) : void
            + one(id :long) : Department
            + replaceDepartment(newDepartment : Department, id :long) Department
            + deleteDepartment(id :long) : void

            + addEmployee(employee : Employee) : void
            + fireEmployee(employee : Employee) : void
        }

        class DepartmentNotFoundAdvice{
            + DepartmentNotFoundHandler(ex : DepartmentNotFoundException) : string
        }

        class DepartmentNotFoundException{
            + DepartmentNotFoundException(id :long) : void
        }

        class EmployeeNotAvailableException{
            + EmployeeNotAvailableException(id :long) : void
        }

        class EmployeeNotFoundAdvice{
            + employeeNotFoundHandler(ex : EmployeeNotFoundException) : string
        }

        class EmployeeNotFoundException{
            + EmployeeNotFoundException(id :long) : void
        }
    }
}
package "Domain"
{
    package "Entities"
    {
        class Employee{
            - id : long
            - name : string
            - email : string
            - role : string

            + equals(o : Object) : boolean
            + hashCode() : int
            + toString() : string
        }

        class Department {
            ' - id : long
            - name : string
            
            + Department()
            + Department(employee : Employee)
            + availibleEmployee(employee : Employee)
        }
    }
}

package "Repositories"
{
    interface EmployeeRepository{}
    interface DepartmentRepository{}
}

'relations
EmployeeController --> Employee
EmployeeController --> EmployeeRepository

EmployeeController ..> EmployeeNotFoundException : throws
EmployeeNotFoundAdvice --> EmployeeNotFoundException

DepartmentController --> Employee
DepartmentController --> department
DepartmentController --> departmentRepository

DepartmentController ..> DepartmentNotFoundAdvice : throws
DepartmentController ..> EmployeeNotAvailableException : throws
DepartmentNotFoundAdvice --> DepartmentNotFoundException

@enduml